/**
 * Catapult REST API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.11
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The AccountMetaDTO model module.
* @module model/AccountMetaDTO
* @version 1.0.11
*/
export default class AccountMetaDTO {
    /**
    * Constructs a new <code>AccountMetaDTO</code>.
    * @alias module:model/AccountMetaDTO
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>AccountMetaDTO</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/AccountMetaDTO} obj Optional instance to populate.
    * @return {module:model/AccountMetaDTO} The populated <code>AccountMetaDTO</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AccountMetaDTO();

            
            
            

        }
        return obj;
    }









}


