/**
 * Catapult REST API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.11
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The AccountPropertyDTO model module.
* @module model/AccountPropertyDTO
* @version 1.0.11
*/
export default class AccountPropertyDTO {
    /**
    * Constructs a new <code>AccountPropertyDTO</code>.
    * @alias module:model/AccountPropertyDTO
    * @class
    * @param propertyType {Number} 
    * @param values {Array.<Object>} 
    */

    constructor(propertyType, values) {
        

        
        

        this['propertyType'] = propertyType;this['values'] = values;

        
    }

    /**
    * Constructs a <code>AccountPropertyDTO</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/AccountPropertyDTO} obj Optional instance to populate.
    * @return {module:model/AccountPropertyDTO} The populated <code>AccountPropertyDTO</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AccountPropertyDTO();

            
            
            

            if (data.hasOwnProperty('propertyType')) {
                obj['propertyType'] = ApiClient.convertToType(data['propertyType'], 'Number');
            }
            if (data.hasOwnProperty('values')) {
                obj['values'] = ApiClient.convertToType(data['values'], [Object]);
            }
        }
        return obj;
    }

    /**
    * @member {Number} propertyType
    */
    propertyType = undefined;
    /**
    * @member {Array.<Object>} values
    */
    values = undefined;








}


