// Copyright 2019 ProximaX Limited. All rights reserved.
// Use of this source code is governed by the Apache 2.0
// license that can be found in the LICENSE file

/**
 * Catapult REST API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.13
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import FieldDTO from './FieldDTO';
import MetadataDTO from './MetadataDTO';





/**
* The AddressMetadataDTO model module.
* @module model/AddressMetadataDTO
* @version 1.0.13
*/
export default class AddressMetadataDTO extends MetadataDTO {
    /**
    * Constructs a new <code>AddressMetadataDTO</code>.
    * @alias module:model/AddressMetadataDTO
    * @class
    * @implements module:model/MetadataDTO
    * @param metadataType {Number} 
    * @param fields {Array.<module:model/FieldDTO>} 
    * @param metadataId {String} 
    */

    constructor(metadataType, fields, metadataId) {
        

        
        super(metadataType, fields);

        this['metadataId'] = metadataId;

        
    }

    /**
    * Constructs a <code>AddressMetadataDTO</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/AddressMetadataDTO} obj Optional instance to populate.
    * @return {module:model/AddressMetadataDTO} The populated <code>AddressMetadataDTO</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AddressMetadataDTO();

            
            
            MetadataDTO.constructFromObject(data, obj);

            if (data.hasOwnProperty('metadataId')) {
                obj['metadataId'] = ApiClient.convertToType(data['metadataId'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} metadataId
    */
    metadataId = undefined;


    // Implement MetadataDTO interface:
    /**
    * @member {Number} metadataType
    */
    metadataType = undefined;
/**
    * @member {Array.<module:model/FieldDTO>} fields
    */
    fields = undefined;







}
