/*
 * Copyright 2019 NEM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 * Catapult REST API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.13
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import FieldDTO from './FieldDTO';
import MetadataDTO from './MetadataDTO';





/**
* The AddressMetadataDTO model module.
* @module model/AddressMetadataDTO
* @version 1.0.13
*/
export default class AddressMetadataDTO {
    /**
    * Constructs a new <code>AddressMetadataDTO</code>.
    * @alias module:model/AddressMetadataDTO
    * @class
    * @implements module:model/MetadataDTO
    * @param metadataType {Number} 
    * @param fields {Array.<module:model/FieldDTO>} 
    * @param metadataId {String} 
    */

    constructor(metadataType, fields, metadataId) {
        

        
        MetadataDTO.call(this, metadataType, fields);

        this['metadataId'] = metadataId;

        
    }

    /**
    * Constructs a <code>AddressMetadataDTO</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/AddressMetadataDTO} obj Optional instance to populate.
    * @return {module:model/AddressMetadataDTO} The populated <code>AddressMetadataDTO</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AddressMetadataDTO();

            
            
            MetadataDTO.constructFromObject(data, obj);

            if (data.hasOwnProperty('metadataId')) {
                obj['metadataId'] = ApiClient.convertToType(data['metadataId'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} metadataId
    */
    metadataId = undefined;


    // Implement MetadataDTO interface:
    /**
    * @member {Number} metadataType
    */
    metadataType = undefined;
/**
    * @member {Array.<module:model/FieldDTO>} fields
    */
    fields = undefined;







}
