// Copyright 2019 ProximaX Limited. All rights reserved.
// Use of this source code is governed by the Apache 2.0
// license that can be found in the LICENSE file

/**
 * Catapult REST API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.13
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import AddressMetadataDTO from './AddressMetadataDTO';





/**
* The AddressMetadataInfoDTO model module.
* @module model/AddressMetadataInfoDTO
* @version 1.0.13
*/
export default class AddressMetadataInfoDTO {
    /**
    * Constructs a new <code>AddressMetadataInfoDTO</code>.
    * @alias module:model/AddressMetadataInfoDTO
    * @class
    * @param metadata {module:model/AddressMetadataDTO} 
    */

    constructor(metadata) {
        

        
        

        this['metadata'] = metadata;

        
    }

    /**
    * Constructs a <code>AddressMetadataInfoDTO</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/AddressMetadataInfoDTO} obj Optional instance to populate.
    * @return {module:model/AddressMetadataInfoDTO} The populated <code>AddressMetadataInfoDTO</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AddressMetadataInfoDTO();

            
            
            

            if (data.hasOwnProperty('metadata')) {
                obj['metadata'] = AddressMetadataDTO.constructFromObject(data['metadata']);
            }
        }
        return obj;
    }

    /**
    * @member {module:model/AddressMetadataDTO} metadata
    */
    metadata = undefined;








}
