/**
 * Catapult REST API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.11
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The AnnounceTransactionInfoDTO model module.
* @module model/AnnounceTransactionInfoDTO
* @version 1.0.11
*/
export default class AnnounceTransactionInfoDTO {
    /**
    * Constructs a new <code>AnnounceTransactionInfoDTO</code>.
    * @alias module:model/AnnounceTransactionInfoDTO
    * @class
    * @param message {String} 
    */

    constructor(message) {
        

        
        

        this['message'] = message;

        
    }

    /**
    * Constructs a <code>AnnounceTransactionInfoDTO</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/AnnounceTransactionInfoDTO} obj Optional instance to populate.
    * @return {module:model/AnnounceTransactionInfoDTO} The populated <code>AnnounceTransactionInfoDTO</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AnnounceTransactionInfoDTO();

            
            
            

            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} message
    */
    message = undefined;








}


