/*
 * Copyright 2019 NEM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 * Catapult REST API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.13
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import UInt64DTO from './UInt64DTO';





/**
* The ContractDTO model module.
* @module model/ContractDTO
* @version 1.0.13
*/
export default class ContractDTO {
    /**
    * Constructs a new <code>ContractDTO</code>.
    * @alias module:model/ContractDTO
    * @class
    * @param multisig {String} 
    * @param multisigAddress {String} 
    * @param start {module:model/UInt64DTO} 
    * @param duration {module:model/UInt64DTO} 
    * @param hash {String} 
    * @param customers {Array.<String>} 
    * @param executors {Array.<String>} 
    * @param verifiers {Array.<String>} 
    */

    constructor(multisig, multisigAddress, start, duration, hash, customers, executors, verifiers) {
        

        
        

        this['multisig'] = multisig;this['multisigAddress'] = multisigAddress;this['start'] = start;this['duration'] = duration;this['hash'] = hash;this['customers'] = customers;this['executors'] = executors;this['verifiers'] = verifiers;

        
    }

    /**
    * Constructs a <code>ContractDTO</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ContractDTO} obj Optional instance to populate.
    * @return {module:model/ContractDTO} The populated <code>ContractDTO</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ContractDTO();

            
            
            

            if (data.hasOwnProperty('multisig')) {
                obj['multisig'] = ApiClient.convertToType(data['multisig'], 'String');
            }
            if (data.hasOwnProperty('multisigAddress')) {
                obj['multisigAddress'] = ApiClient.convertToType(data['multisigAddress'], 'String');
            }
            if (data.hasOwnProperty('start')) {
                obj['start'] = UInt64DTO.constructFromObject(data['start']);
            }
            if (data.hasOwnProperty('duration')) {
                obj['duration'] = UInt64DTO.constructFromObject(data['duration']);
            }
            if (data.hasOwnProperty('hash')) {
                obj['hash'] = ApiClient.convertToType(data['hash'], 'String');
            }
            if (data.hasOwnProperty('customers')) {
                obj['customers'] = ApiClient.convertToType(data['customers'], ['String']);
            }
            if (data.hasOwnProperty('executors')) {
                obj['executors'] = ApiClient.convertToType(data['executors'], ['String']);
            }
            if (data.hasOwnProperty('verifiers')) {
                obj['verifiers'] = ApiClient.convertToType(data['verifiers'], ['String']);
            }
        }
        return obj;
    }

    /**
    * @member {String} multisig
    */
    multisig = undefined;
    /**
    * @member {String} multisigAddress
    */
    multisigAddress = undefined;
    /**
    * @member {module:model/UInt64DTO} start
    */
    start = undefined;
    /**
    * @member {module:model/UInt64DTO} duration
    */
    duration = undefined;
    /**
    * @member {String} hash
    */
    hash = undefined;
    /**
    * @member {Array.<String>} customers
    */
    customers = undefined;
    /**
    * @member {Array.<String>} executors
    */
    executors = undefined;
    /**
    * @member {Array.<String>} verifiers
    */
    verifiers = undefined;








}
