// Copyright 2019 ProximaX Limited. All rights reserved.
// Use of this source code is governed by the Apache 2.0
// license that can be found in the LICENSE file

/**
 * Catapult REST API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.13
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The FieldDTO model module.
* @module model/FieldDTO
* @version 1.0.13
*/
export default class FieldDTO {
    /**
    * Constructs a new <code>FieldDTO</code>.
    * @alias module:model/FieldDTO
    * @class
    * @param key {String} 
    * @param value {String} 
    */

    constructor(key, value) {
        

        
        

        this['key'] = key;this['value'] = value;

        
    }

    /**
    * Constructs a <code>FieldDTO</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/FieldDTO} obj Optional instance to populate.
    * @return {module:model/FieldDTO} The populated <code>FieldDTO</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FieldDTO();

            
            
            

            if (data.hasOwnProperty('key')) {
                obj['key'] = ApiClient.convertToType(data['key'], 'String');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} key
    */
    key = undefined;
    /**
    * @member {String} value
    */
    value = undefined;








}
