/**
 * Catapult REST API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.11
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import MerkleProofInfoPayload from './MerkleProofInfoPayload';





/**
* The MerkleProofInfoDTO model module.
* @module model/MerkleProofInfoDTO
* @version 1.0.11
*/
export default class MerkleProofInfoDTO {
    /**
    * Constructs a new <code>MerkleProofInfoDTO</code>.
    * @alias module:model/MerkleProofInfoDTO
    * @class
    * @param payload {module:model/MerkleProofInfoPayload} 
    * @param type {String} 
    */

    constructor(payload, type) {
        

        
        

        this['payload'] = payload;this['type'] = type;

        
    }

    /**
    * Constructs a <code>MerkleProofInfoDTO</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/MerkleProofInfoDTO} obj Optional instance to populate.
    * @return {module:model/MerkleProofInfoDTO} The populated <code>MerkleProofInfoDTO</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MerkleProofInfoDTO();

            
            
            

            if (data.hasOwnProperty('payload')) {
                obj['payload'] = MerkleProofInfoPayload.constructFromObject(data['payload']);
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {module:model/MerkleProofInfoPayload} payload
    */
    payload = undefined;
    /**
    * @member {String} type
    */
    type = undefined;








}


