/**
 * Catapult REST API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.11
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The MerklePathItem model module.
* @module model/MerklePathItem
* @version 1.0.11
*/
export default class MerklePathItem {
    /**
    * Constructs a new <code>MerklePathItem</code>.
    * @alias module:model/MerklePathItem
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>MerklePathItem</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/MerklePathItem} obj Optional instance to populate.
    * @return {module:model/MerklePathItem} The populated <code>MerklePathItem</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MerklePathItem();

            
            
            

            if (data.hasOwnProperty('position')) {
                obj['position'] = ApiClient.convertToType(data['position'], 'Number');
            }
            if (data.hasOwnProperty('hash')) {
                obj['hash'] = ApiClient.convertToType(data['hash'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {Number} position
    */
    position = undefined;
    /**
    * @member {String} hash
    */
    hash = undefined;








}


