// Copyright 2019 ProximaX Limited. All rights reserved.
// Use of this source code is governed by the Apache 2.0
// license that can be found in the LICENSE file

/**
 * Catapult REST API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.13
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import FieldDTO from './FieldDTO';





/**
* The MetadataDTO model module.
* @module model/MetadataDTO
* @version 1.0.13
*/
export default class MetadataDTO {
    /**
    * Constructs a new <code>MetadataDTO</code>.
    * @alias module:model/MetadataDTO
    * @class
    * @param metadataType {Number} 
    * @param fields {Array.<module:model/FieldDTO>} 
    */

    constructor(metadataType, fields) {
        

        
        

        this['metadataType'] = metadataType;this['fields'] = fields;

        
    }

    /**
    * Constructs a <code>MetadataDTO</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/MetadataDTO} obj Optional instance to populate.
    * @return {module:model/MetadataDTO} The populated <code>MetadataDTO</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MetadataDTO();

            
            
            

            if (data.hasOwnProperty('metadataType')) {
                obj['metadataType'] = ApiClient.convertToType(data['metadataType'], 'Number');
            }
            if (data.hasOwnProperty('fields')) {
                obj['fields'] = ApiClient.convertToType(data['fields'], [FieldDTO]);
            }
        }
        return obj;
    }

    /**
    * @member {Number} metadataType
    */
    metadataType = undefined;
    /**
    * @member {Array.<module:model/FieldDTO>} fields
    */
    fields = undefined;








}
