// Copyright 2019 ProximaX Limited. All rights reserved.
// Use of this source code is governed by the Apache 2.0
// license that can be found in the LICENSE file

/**
 * Catapult REST API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.13
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The MetadataIds model module.
* @module model/MetadataIds
* @version 1.0.13
*/
export default class MetadataIds {
    /**
    * Constructs a new <code>MetadataIds</code>.
    * @alias module:model/MetadataIds
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>MetadataIds</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/MetadataIds} obj Optional instance to populate.
    * @return {module:model/MetadataIds} The populated <code>MetadataIds</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MetadataIds();

            
            
            

            if (data.hasOwnProperty('metadataIds')) {
                obj['metadataIds'] = ApiClient.convertToType(data['metadataIds'], ['String']);
            }
        }
        return obj;
    }

    /**
    * @member {Array.<String>} metadataIds
    */
    metadataIds = undefined;








}
