/**
 * Catapult REST API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.11
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import MultisigAccountInfoDTO from './MultisigAccountInfoDTO';





/**
* The MultisigAccountGraphInfoDTO model module.
* @module model/MultisigAccountGraphInfoDTO
* @version 1.0.11
*/
export default class MultisigAccountGraphInfoDTO {
    /**
    * Constructs a new <code>MultisigAccountGraphInfoDTO</code>.
    * @alias module:model/MultisigAccountGraphInfoDTO
    * @class
    * @param level {Number} 
    * @param multisigEntries {Array.<module:model/MultisigAccountInfoDTO>} 
    */

    constructor(level, multisigEntries) {
        

        
        

        this['level'] = level;this['multisigEntries'] = multisigEntries;

        
    }

    /**
    * Constructs a <code>MultisigAccountGraphInfoDTO</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/MultisigAccountGraphInfoDTO} obj Optional instance to populate.
    * @return {module:model/MultisigAccountGraphInfoDTO} The populated <code>MultisigAccountGraphInfoDTO</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MultisigAccountGraphInfoDTO();

            
            
            

            if (data.hasOwnProperty('level')) {
                obj['level'] = ApiClient.convertToType(data['level'], 'Number');
            }
            if (data.hasOwnProperty('multisigEntries')) {
                obj['multisigEntries'] = ApiClient.convertToType(data['multisigEntries'], [MultisigAccountInfoDTO]);
            }
        }
        return obj;
    }

    /**
    * @member {Number} level
    */
    level = undefined;
    /**
    * @member {Array.<module:model/MultisigAccountInfoDTO>} multisigEntries
    */
    multisigEntries = undefined;








}


