/*
 * Copyright 2018 NEM
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NIS2 API
 * This document defines all the nis2 api routes and behaviour
 *
 * OpenAPI spec version: 1.0.0
 * Contact: guillemchain@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The Multisig model module.
* @module model/Multisig
* @version 1.0.0
*/
export default class Multisig {
    /**
    * Constructs a new <code>Multisig</code>.
    * @alias module:model/Multisig
    * @class
    * @param account {String} 
    * @param minApproval {Number} 
    * @param minRemoval {Number} 
    * @param cosignatories {Array.<String>} 
    * @param multisigAccounts {Array.<String>} 
    */

    constructor(account, minApproval, minRemoval, cosignatories, multisigAccounts) {
        

        
        

        this['account'] = account;this['minApproval'] = minApproval;this['minRemoval'] = minRemoval;this['cosignatories'] = cosignatories;this['multisigAccounts'] = multisigAccounts;

        
    }

    /**
    * Constructs a <code>Multisig</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Multisig} obj Optional instance to populate.
    * @return {module:model/Multisig} The populated <code>Multisig</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Multisig();

            
            
            

            if (data.hasOwnProperty('account')) {
                obj['account'] = ApiClient.convertToType(data['account'], 'String');
            }
            if (data.hasOwnProperty('accountAddress')) {
                obj['accountAddress'] = ApiClient.convertToType(data['accountAddress'], 'String');
            }
            if (data.hasOwnProperty('minApproval')) {
                obj['minApproval'] = ApiClient.convertToType(data['minApproval'], 'Number');
            }
            if (data.hasOwnProperty('minRemoval')) {
                obj['minRemoval'] = ApiClient.convertToType(data['minRemoval'], 'Number');
            }
            if (data.hasOwnProperty('cosignatories')) {
                obj['cosignatories'] = ApiClient.convertToType(data['cosignatories'], ['String']);
            }
            if (data.hasOwnProperty('multisigAccounts')) {
                obj['multisigAccounts'] = ApiClient.convertToType(data['multisigAccounts'], ['String']);
            }
        }
        return obj;
    }

    /**
    * @member {String} account
    */
    account = undefined;
    /**
    * @member {String} accountAddress
    */
    accountAddress = undefined;
    /**
    * @member {Number} minApproval
    */
    minApproval = undefined;
    /**
    * @member {Number} minRemoval
    */
    minRemoval = undefined;
    /**
    * @member {Array.<String>} cosignatories
    */
    cosignatories = undefined;
    /**
    * @member {Array.<String>} multisigAccounts
    */
    multisigAccounts = undefined;








}


