/**
 * Catapult REST API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.11
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import NamespaceDTO from './NamespaceDTO';
import NamespaceMosaicMetaDTO from './NamespaceMosaicMetaDTO';





/**
* The NamespaceInfoDTO model module.
* @module model/NamespaceInfoDTO
* @version 1.0.11
*/
export default class NamespaceInfoDTO {
    /**
    * Constructs a new <code>NamespaceInfoDTO</code>.
    * @alias module:model/NamespaceInfoDTO
    * @class
    * @param namespace {module:model/NamespaceDTO} 
    */

    constructor(namespace) {
        

        
        

        this['namespace'] = namespace;

        
    }

    /**
    * Constructs a <code>NamespaceInfoDTO</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/NamespaceInfoDTO} obj Optional instance to populate.
    * @return {module:model/NamespaceInfoDTO} The populated <code>NamespaceInfoDTO</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NamespaceInfoDTO();

            
            
            

            if (data.hasOwnProperty('meta')) {
                obj['meta'] = NamespaceMosaicMetaDTO.constructFromObject(data['meta']);
            }
            if (data.hasOwnProperty('namespace')) {
                obj['namespace'] = NamespaceDTO.constructFromObject(data['namespace']);
            }
        }
        return obj;
    }

    /**
    * @member {module:model/NamespaceMosaicMetaDTO} meta
    */
    meta = undefined;
    /**
    * @member {module:model/NamespaceDTO} namespace
    */
    namespace = undefined;








}


