/**
 * Catapult REST API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.11
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The NamespaceMosaicMetaDTO model module.
* @module model/NamespaceMosaicMetaDTO
* @version 1.0.11
*/
export default class NamespaceMosaicMetaDTO {
    /**
    * Constructs a new <code>NamespaceMosaicMetaDTO</code>.
    * @alias module:model/NamespaceMosaicMetaDTO
    * @class
    * @param active {Boolean} 
    * @param index {Number} 
    * @param id {String} 
    */

    constructor(active, index, id) {
        

        
        

        this['active'] = active;this['index'] = index;this['id'] = id;

        
    }

    /**
    * Constructs a <code>NamespaceMosaicMetaDTO</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/NamespaceMosaicMetaDTO} obj Optional instance to populate.
    * @return {module:model/NamespaceMosaicMetaDTO} The populated <code>NamespaceMosaicMetaDTO</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NamespaceMosaicMetaDTO();

            
            
            

            if (data.hasOwnProperty('active')) {
                obj['active'] = ApiClient.convertToType(data['active'], 'Boolean');
            }
            if (data.hasOwnProperty('index')) {
                obj['index'] = ApiClient.convertToType(data['index'], 'Number');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {Boolean} active
    */
    active = undefined;
    /**
    * @member {Number} index
    */
    index = undefined;
    /**
    * @member {String} id
    */
    id = undefined;








}


