/**
 * Catapult REST API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.11
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import CommunicationTimestamps from './CommunicationTimestamps';





/**
* The NodeTimeDTO model module.
* @module model/NodeTimeDTO
* @version 1.0.11
*/
export default class NodeTimeDTO {
    /**
    * Constructs a new <code>NodeTimeDTO</code>.
    * @alias module:model/NodeTimeDTO
    * @class
    * @param communicationTimestamps {module:model/CommunicationTimestamps} 
    */

    constructor(communicationTimestamps) {
        

        
        

        this['communicationTimestamps'] = communicationTimestamps;

        
    }

    /**
    * Constructs a <code>NodeTimeDTO</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/NodeTimeDTO} obj Optional instance to populate.
    * @return {module:model/NodeTimeDTO} The populated <code>NodeTimeDTO</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NodeTimeDTO();

            
            
            

            if (data.hasOwnProperty('communicationTimestamps')) {
                obj['communicationTimestamps'] = CommunicationTimestamps.constructFromObject(data['communicationTimestamps']);
            }
        }
        return obj;
    }

    /**
    * @member {module:model/CommunicationTimestamps} communicationTimestamps
    */
    communicationTimestamps = undefined;








}


