/**
 * Catapult REST API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.11
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The TransactionIds model module.
* @module model/TransactionIds
* @version 1.0.11
*/
export default class TransactionIds {
    /**
    * Constructs a new <code>TransactionIds</code>.
    * @alias module:model/TransactionIds
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>TransactionIds</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/TransactionIds} obj Optional instance to populate.
    * @return {module:model/TransactionIds} The populated <code>TransactionIds</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TransactionIds();

            
            
            

            if (data.hasOwnProperty('transactionIds')) {
                obj['transactionIds'] = ApiClient.convertToType(data['transactionIds'], ['String']);
            }
        }
        return obj;
    }

    /**
    * @member {Array.<String>} transactionIds
    */
    transactionIds = undefined;








}


