/**
 * Catapult REST API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.11
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The UInt64DTO model module.
* @module model/UInt64DTO
* @version 1.0.11
*/
export default class UInt64DTO extends Array {
    /**
    * Constructs a new <code>UInt64DTO</code>.
    * @alias module:model/UInt64DTO
    * @class
    * @extends Array
    */

    constructor() {
        
        super();
        

        
        

        

        return this;
    }

    /**
    * Constructs a <code>UInt64DTO</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/UInt64DTO} obj Optional instance to populate.
    * @return {module:model/UInt64DTO} The populated <code>UInt64DTO</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UInt64DTO();

            ApiClient.constructFromObject(data, obj, 'Number');

            
            

        }
        return obj;
    }









}


